base_url = "https://david.kolo.ski"

title = "David Koloski"
description = "I'm a software engineer!"

generate_feeds = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags"}
]

compile_sass = true

build_search_index = true

[markdown]
bottom_footnotes = true

[markdown.highlighting]
error_on_missing_language = true
theme = "github-light-default"

[extra]
author = { name = "David Koloski" }